name: tests_denormalized
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python
      run: |
        pip3 install -r requirements.txt
    - name: docker
      run: |
        git submodule init
        git submodule update
        docker compose up -d --build
        docker ps -a
        until pg_isready -h localhost -p 5435; do sleep 1; done
        sh load_tweets.sh
        export PGPOORT=5435 
        bash run_tests.sh
